### ISSUE TITLE
Aspect ratio not working as expected

### ISSUE THREAD

**Issue by jeppeschibsted** [warp-ds/drive#158]
Using class `aspect-4/3` results in css of:
```css
.aspect-4\/3 {
    position: relative;
    padding-bottom: 75%;
}
```

expected css:  
```css
.aspect-4\/3 {
    aspect-ratio: 4 / 3;
}
```

CSS `aspect-ratio` is well supported: https://caniuse.com/mdn-css_properties_aspect-ratio
